export default {
    skuQcResult:{
        showType:'qc',
        value:'Waiting QC'
    },
    skuCode:{},
    customerSkuCode:{},
    factorySkuCode:{},
    skuNameCn:{},
    skuBrand:{},
    //产品设计
    packingMethodCn:{},
    innerCartonPackingMethodCn:{},
    //delivery date
    skuUnitDictCode:{},
    //三个unit单位
    inboundNo:{},
    orderSkuQty:{},
    expectQcQty:{
        key:'expectQcQty',
        showType:'number'
    },
    samplingRate:{
        key:'samplingRate',
        showType:'number'
    },
    unqualifiedProcessingMode:{
        key:'unqualifiedProcessingMode',
        showType:'input'
    },
    //外箱数合计
    skuLength:{},
    skuWidth:{},
    skuHeight:{},
    skuNetWeight:{},
    outerCartonSkuQty:{},
    actQtyOfOuterCarton:{
        fromService:true
    },
    //外箱中包数
    actQuantityOfInnerBoxOuterCarton:{
        fromService:true
    },
    //中包产品数
    actualQuantityInnerCarton:{
        fromService:true
    },
    innerCartonLength:{
        fromService:true
    },
    innerCartonWidth:{
        fromService:true
    },
    innerCartonHeight:{
        fromService:true
    },
    innerCartonNetWeight:{
        fromService:true
    },
    innerCartonGrossWeight:{
        fromService:true
    },
    innerCartonVolume:{
        fromService:true
    },
    outerCartonLength:{
        fromService:true
    },
    outerCartonWidth:{
        fromService:true
    },
    outerCartonHeight:{
        fromService:true
    },
    netWeightOfOuterCarton:{
        fromService:true
    },
    outerCartonVolume:{
        fromService:true
    },
    grossWeightOfOuterCarton:{
        fromService:true
    },
    actualProductTotalCTNS:{
        fromService:true
    },
    qualifiedProductsTotalCTNS:{
        fromService:true
    },
    unqualifiedProductTotalCTNS:{
        fromService:true
    },
    actProductQuantity:{
        fromService:true
    },
    qualifiedProductsTotalQTYS:{
        fromService:true
    },
    unqualifiedProductsQTY:{
        fromService:true
    },
    qualifiedProductTotalNW:{
        fromService:true
    },
    unqualifiedProductTotalNW:{
        fromService:true
    },
    qualifiedProductsTotalCBM:{
        fromService:true
    },
    unqualifiedProductsTotalCBM:{
        fromService:true
    },
    qualifiedProductTotalGW:{
        fromService:true
    },
    unqualifiedProductTotalGW:{
        fromService:true
    },
    unqualifiedType:{
        fromService:true
    },
    skuBarCode:{},
    productBarCodeResults:{
        fromService:true
    },
    skuLabel:{},
    productLabelResults:{
        fromService:true
    },
    //中包条码
    innerPackingBarCodeResults:{
        fromService:true
    },
    //外箱条码
    outerCartonBarCodeResults:{
        fromService:true
    },
    //外箱唛头
    outerCartonMarksResults:{
        fromService:true
    },
    qcPic:{
        fromService:true
    },
    checkOuterCartons:{
        fromService:true
    },
    remark:{
        fromService:true
    },

}