export default {
    id: {
        _hide:true
    },
    skuBarCode:{},
    skuCode:{
        key:'skuCode',
    },
    skuNameCn:{
        key:'skuNameCn',
    },
    skuNameEn:{
        key:'skuNameEn',
    },
    skuNameCustomer: {},
    skuMaterialCn:{
        key:'skuMaterialCn',
    },
    skuMaterialEn:{
        key:'skuMaterialEn',
    },
    factorySkuCode:{
        key:'factorySkuCode',
    },
    customerSkuCode:{
        key:'customerSkuCode',
    },

    skuUnitDictCode:{
        key:'skuUnitDictCode',
        showType:'select',
        options:[
            {
                label:'kg',
                value:1
            },
            {
                label:'g',
                value:2
            }
        ]
    },
  lengthUnitDictCode:{
        key:'lengthUnitDictCode',
    },
  volumeUnitDictCode:{
        key:'volumeUnitDictCode',
    },
  weightUnitDictCode:{
        key:'weightUnitDictCode',
    },
    outboundSkuTotalQty:{   //出库产品总数量
        key:'outboundSkuTotalQty',
        showType:'number',
        computed:true
    },
    outboundOutCartonTotalQty:{
        key:'outboundOutCartonTotalQty',        //需要传的参数
        showType:'number',
        isNeed:true,
        _rules:{
            required:true,
            type:'Number'
        }
    },
    outboundSkuTotalVolume:{
        key:'outboundSkuTotalVolume',
        showType:'number',
        computed:true
    },
    outboundSkuTotalNetWeight:{
        key:'outboundSkuTotalNetWeight',
        showType:'number',
        computed:true
    },
    outboundSkuTotalGrossWeight:{
        key:'outboundSkuTotalGrossWeight',
        showType:'number',
        computed:true
    },
    outerCartonSkuQty:{         //外箱产品数
        key:'outerCartonSkuQty',
    },
    outerCartonVolume:{
        key:'outerCartonVolume',
    },
    outerCartonGrossWeight:{
        key:'outerCartonGrossWeight',
    },
    outerCartonNetWeight:{
        key:'outerCartonNetWeight',
    },
    inboundNo:{ //入库单号
        key:'inboundNo',
    },
    skuDescEn:{
        key:'skuDescEn',
    },
    skuDescCn:{
        key:'skuDescCn',
    },
    skuDescCustomer:{
        key:'skuDescCustomer',
    },
    skuLabel:{
        key:'skuLabel',
    },
    orderNo:{
        key:'orderNo',
    },
    warehouseNo:{
        key:'warehouseNo'
    },
    warehouseName:{
        key:'warehouseName'
    },
    inboundDate:{
        key:'inboundDate',
    },
    inventoryDays:{
        key:'inventoryDays',
        showType:'number',
    },
    inventorySkuPrice:{        //需要传的参数
        key:'inventorySkuPrice',
        showType:'number',
    },
    inventoryServiceFee:{        //需要传的参数
        key:'inventoryServiceFee',
        showType:'number',
    },
    skuBarCode:{
        key:'skuBarCode'
    },
    skuNameCustomer:{
        key:'skuNameCustomer'
    }
}
