export default {
    id:{
        _hide: true
    },
    skuCode:{},
    customerSkuCode:{},
    orderSkuQty:{},
    expectQcQty:{},
    skuQcResultDictCode:{},
    skuInventoryStatusDictCode:{},
    // factorySkuCode:{},
    skuNameCn:{},
    skuBrand:{},
    skuDesign:{},
    packingMethodCn:{},
    innerCartonPackingMethodCn:{},
    deliveryDate:{},
    skuMethodPkgEn:{},
    skuInnerCartonMethodEn:{},
    skuUnitDictCode:{},
    inboundNo:{},
    samplingRate:{},
    checkOuterCartonQty:{},
    unqualifiedProcessingMode:{},
    skuLength:{},
    skuWidth:{},
    skuHeight:{},
    skuNetWeight:{},
    outerCartonSkuQty:{},
    actOuterCartonSkuQty:{},
    outerCartonInnerBoxQty:{},
    actOuterCartonInnerBoxQty:{},
    innerCartonSkuQty:{},
    actInnerCartonSkuQty:{},
    innerCartonLength:{},
    innerCartonWidth:{},
    innerCartonHeight:{},
    innerCartonNetWeight:{},
    innerCartonGrossWeight:{},
    innerCartonVolume:{},
    outerCartonLength:{},
    outerCartonWidth:{},
    outerCartonHeight:{},
    outerCartonNetWeight:{},
    outerCartonVolume:{},
    outerCartonGrossWeight:{},
    actSkuCartonTotalQty:{},
    qualifiedSkuCartonTotalQty:{},
    unqualifiedSkuCartonTotalQty:{},
    qualifiedSkuQty:{},
    unqualifiedSkuQty:{},
    qualifiedSkuNetWeight:{},
    unqualifiedSkuNetWeight:{
        width: '200'
    },
    qualifiedSkuVolume:{},
    unqualifiedSkuVolume:{
        width: '200'
    },
    qualifiedSkuGrossWeight:{},
    unqualifiedSkuGrossWeight:{
        width: '200'
    },
    unqualifiedType:{},
    skuBarCode:{},
    skuBarCodeResultDictCode:{},
    skuLabel:{},
    skuLabelResultDictCode:{},
    innerPackingBarCode:{},
    innerPackingBarCodeResultDictCode:{},
    innerCartonMark:{},
    innerCartonMarkResultDictCode:{},
    outerCartonBarCode:{},
    outerCartonBarCodeResultDictCode:{},
    shippingMark:{},
    shippingMarkResultDictCode:{},
    actSkuQty:{},
    qcPic:{
        key:'qcPics',
        sortable: false
    },
    remark:{},
    lengthUnitDictCode:{},
    volumeUnitDictCode:{},
    weightUnitDictCode:{},

}