export default {
    qcOrderNo:{
        key:'qcOrderNo',
        showType:'input'
    },
    qcTypeDictCode:{
        key:'qcTypeDictCode',
        showType:'select',
        isQcType:true
    },
    qcDate:{
        key:'qcDate',
        showType:'date'
    },
    factoryAddress:{
        key:'factoryAddress',
        showType:'input'
    },
    factoryContactPhone:{
        key:'factoryContactPhone',
        showType:'input'
    },
    serviceName:{
        key:'serviceName',
        showType:'input'
    },
    surveyor:{
        key:'surveyor',
        showType:'select'
    },
    exchangeCurrencyDictCode:{
        key:'exchangeCurrencyDictCode',
        showType:'select',
        isCurrency:true
    },
    serviceFee:{
        key:'serviceFee',
        showType:'input',
        isServiceFill:true
    },
    qcMethodDictCode:{
        key:'qcMethodDictCode',
        showType:'select',
        isQcMethod:true,
    },
    qcStatusDictCode:{
        key:'qcStatusDictCode',
        showType:'select',
        isQcStatus:true,
    },
    remark:{
        key:'remark',
        showType:'textarea',
        fullLine:true
    },
    attachment:{
        key:'attachment',
        showType:'textarea',
        fullLine:true
    },
}