export default {
    id:{
        _hide:true
    },
    serviceProviderIsLoginUser:{
        _hide:true
    },
    qcOrderNo:{},
    orderNo:{},
    qcStatusDictCode:{},
    qcMethodDictCode:{},
    surveyor:{},
    factoryAddress:{},
    factoryContactPhone:{},
    remark:{},
    qualifiedSkuCartonTotalQty:{},
    qualifiedSkuQty:{},
    qualifiedSkuVolume:{},
    qualifiedSkuNetWeight:{},
    qualifiedSkuGrossWeight:{},
    unqualifiedSkuQty:{},
    unqualifiedSkuCartonTotalQty:{},
    unqualifiedSkuNetWeight:{},
    unqualifiedSkuVolume:{},
    unqualifiedSkuGrossWeight:{},
    skuRowNum:{},
}