export default {
    id:{
        _hide:true
    },
    skuId:{
        _hide:true
    },
    skuPics: {
        _image:true,
        _sort:false
    },
    skuInventoryStatusDictCode:{},
    skuQcStatusDictCode:{},
    // warehouseNo:{},
    warehouseName:{},
    orderNo:{},
    skuCode:{},
    customerAbbr:{},
    skuNameCn:{},
    inboundOutCartonTotalQty:{},
    outboundOutCartonTotalQty:{},
    inventoryOutCartonQty:{},
    inboundSkuTotalQty:{},
    inventorySkuQty:{},
    inventorySkuVolume:{},
    inventorySkuGrossWeight:{},
    inventorySkuNetWeight:{},
    skuBarCode:{},
    outboundSkuTotalQty:{},
    outerCartonSkuQty:{},
    outerCartonNetWeight:{},
    outerCartonGrossWeight:{},
    outerCartonVolume:{},
    // innerCartonLength:{},
    // innerCartonWidth:{},
    // innerCartonHeight:{},
    // innerCartonNetWeight:{},
    // innerCartonGrossWeight:{},
    // innerCartonVolume:{},
    // skuLength:{},
    // skuWidth:{},
    // skuHeight:{},
    skuNetWeight:{},
    skuNameEn:{},
    skuDescEn:{},
    skuUnitDictCode:{},
    // skuLabel:{},
    skuBrand:{},
    orderSkuQty:{},
    // customerNo:{},
    customerSkuCode:{},
    // factorySkuCode:{},
    inboundNo:{},
    inboundDate:{},
}
