export default {
    id:{
        _hide:true
    },
    skuId:{
        _hide:true
    },
    skuPics: {
        _image:true,
        _sort:false
    },
    skuInventoryStatusDictCode:{},
    skuQcStatusDictCode:{},
    // warehouseNo:{},
    warehouseName:{},
    skuCode:{},
    skuBarCode:{},
    orderNo:{},
    inboundOutCartonTotalQty:{},
    outboundOutCartonTotalQty:{},
    inventoryOutCartonQty:{},
    inboundSkuTotalQty:{},
    outboundSkuTotalQty:{},
    inventorySkuQty:{},
    inventorySkuVolume:{},
    inventorySkuGrossWeight:{},
    inventorySkuNetWeight:{},
    outerCartonSkuQty:{},
    outerCartonNetWeight:{},
    outerCartonGrossWeight:{},
    outerCartonVolume:{},
    innerCartonLength:{},
    innerCartonWidth:{},
    innerCartonHeight:{},
    innerCartonNetWeight:{},
    innerCartonGrossWeight:{},
    innerCartonVolume:{},
    customerAbbr:{},
    // skuLength:{},
    // skuWidth:{},
    // skuHeight:{},
    skuNetWeight:{},
    skuNameCn:{},
    skuNameEn:{},
    skuDescEn:{},
    skuUnitDictCode:{},
    // skuLabel:{},
    skuBrand:{},
    orderSkuQty:{},
    // customerNo:{},
    customerSkuCode:{},
    // factorySkuCode:{},
    inboundNo:{},
    inboundDate:{},
}
