export default {
    id:{
        _hide:true
    },
    skuId:{
        _hide:true
    },
    customerCreate:{
        _hide:true
    },
    bookmarkId:{
        _hide:true
    },
    pic: {
        key:'pictures',
        _image:true,
        _fixed:'left',
        _sort:false
    },
    code:{
        _fixed:'left'
    },
    nameEn:{},
    descCn:{
        _sort:false
    },
    unit:{},
    fobCurrency:{},
    fobPrice:{},
    exwCurrency:{},
    exwPrice:{},
    availableQty:{},
    outerCartonQty:{},
    materialCn:{},
    innerCartonQty:{},
    innerCartonMethodCn:{
        _sort:false
    },
    methodPkgCn:{
        _sort:false
    },
    skuSaleStatus: {
        key:'status'
    },
    descEn:{
        _sort:false
    },
    minOrderQty:{},
    deliveryDates:{},
    categoryId:{
        key:'categoryName',
        _sort:false
    },
    readilyAvailable:{},
    noneSellCountry:{},
    outerCartonNetWeight:{},
    outerCartonRoughWeight:{},
    outerCartonVolume:{},
    recycle:{},
    nameCn:{},
    nameCustomer:{},
    supplierCode:{},
    formation:{},
    oemQty:{},
    materialEn:{},
    colourEn:{},
    colourCn:{},
    barcode:{
        _sort:false
    },
    applicableAge:{},
    expireDates:{},
    expireUnit:{},
    designs:{
        _upload:{
            readonly:true
        }
    },
    notes:{
        _upload:{
            readonly:true
        }
    },
    fobPort:{
        _sort:false
    },
    cifPrice:{},
    cifCurrency:{},
    cifArea:{
        _sort:false
    },
    dduPrice:{},
    dduCurrency:{},
    dduArea:{
        _sort:false
    },
    rateValueAddedTax:{},
    taxRefundRate:{},
    customsCode:{},
    customsNameCn:{},
    customsNameEn:{},
    tradeMarkCn:{},
    tradeMarkEn:{},
    commodityInspectionCn:{},
    commodityInspectionEn:{},
    declareElement:{
        _sort:false
    },
    origin:{},
    inspectQuarantineCategory:{},
    brand:{
        _sort:false
    },
    brandRemark:{
        _sort:false
    },
    brandRelated:{
        _sort:false
    },
    certificat:{
        _sort:false
    },
    unitWeight:{
        _sort:false
    },
    unitLength:{
        _sort:false
    },
    unitVolume:{
        _sort:false
    },
    length:{},
    width:{},
    height:{},
    netWeight:{},
    volume:{},
    methodPkgEn:{
        _sort:false
    },
    innerCartonLength:{},
    innerCartonWidth:{},
    innerCartonHeight:{},
    innerCartonWeightNet:{},
    innerCartonRoughWeight:{},
    innerCartonVolume:{},
    innerCartonDesc:{
        _sort:false
    },
    innerCartonMethodEn:{
        _sort:false
    },
    outerCartonDesc:{
        _sort:false
    },
    innerCartonOuterNum:{},
    outerCartonLength:{},
    outerCartonWidth:{},
    outerCartonHeight:{},
    outerCartonMethodCn:{
        _sort:false
    },
    outerCartonMethodEn:{
        _sort:false
    },
    oem:{},
    gp20SkuQty:{},
    gp40SkuQty:{},
    hq40SkuQty:{},
    tryDimension:{},
    skuQtyPerTray:{},
    specialTransportRequire:{
        _sort:false
    },
    mainSaleCountry:{
        _sort:false
    },
    mainSaleArea:{
        _sort:false
    },
    qualityStander:{
        _sort:false
    },
    yearListed:{},
    useDisplayBox:{},
    displayBoxQty:{},
    lengthWidthHeight:{},
    otherPackInfoCn:{
        _sort:false
    },
    otherPackInfoEn:{
        _sort:false
    },
    adjustPackage:{},
}
