export default {
    quotationNo:{},
    orderNo:{},
    incoterm:{},
    incotermArea:{},
    currencyTrade:{
        key:'currency'
    },
    unitPrice:{},
    skuPrice:{},
    totalQty:{},
    totalContainerQty:{},
    salesOrderNo:{
        key:'customerOrderNo'
    },
    purchaseOrderNo:{
        key:'supplierOrderNo'
    },
    totalCTN:{
        key:'totalOuterCartonQty'
    },
    orderCreateDt:{},
    qualifiedSkuQty:{},
}