export default {
    quotationNo:{},
    orderNo:{},
    incoterm:{},
    incotermArea:{},
    currency:{},
    unitPrice:{},
    skuPrice:{},
    totalQty:{},
    actDeliveryDt:{},
    totalContainerQty:{},
    salesOrderNo:{
        key:'customerOrderNo'
    },
    purchaseOrderNo:{
        key:'supplierOrderNo'
    },
    totalCTN:{
        key:'totalOuterCartonQty'
    },
    orderCreateDt:{},
    qualifiedSkuQty:{},
}