export default {
    orderNo: {
        key: 'orderNo',
        ismodify: false,
//        isDefaultEdit: true,
        rules: [],
        type: 'text',
    },
    orderDate: {
        key: 'orderDate',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'datepicker',
    },
    customerOrderNo: {
        key: 'customerOrderNo',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    customerName: {
        key: 'customerName',
        ismodify: false,
        isDefaultEdit: true,
        rules: [],
        type: 'text',
    },
    customerNo: {
        key: 'customerNo',
        ismodify: false,
        isDefaultEdit: true,
        rules: [],
        type: 'text',
    },
    supplierOrderNo: {
        key: 'supplierOrderNo',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },

    //弹窗修改
    supplierName: {
        key: 'supplierName',
        ismodify: false,
//        isDefaultEdit: true,
        rules: [],
        type: 'supplierName',
    },
    //弹窗修改
    supplierNo: {
        key: 'supplierCode',
        ismodify: false,
//        isDefaultEdit: true,
        rules: [],
        type: 'supplierNo',
    },
    quotationNo: {
        key: 'quotationNo',
        ismodify: false,
        isDefaultEdit: true,
        rules: [],
        type: 'text',
    },
    orderStatus: {
        key: 'status',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'status',
    },
    deliveryDate: {
        key: 'deliveryDt',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'datepicker',
    },
    incoterm: {
        key: 'incoterm',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'select',
    },
    currency: {
        key: 'currency',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'currency',
    },
    incortermAea: {
        key: 'incortermAea',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    payment: {
        key: 'payment',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'select',
    },
    lcNo: {
        key: 'lcNo',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    paymentDays: {
        key: 'paymentDays',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    paymentStatus: {
        key: 'paymentStatus',
        ismodify: false,
        isDefaultEdit: true,
        rules: [],
        type: 'text',
    },
    departureCountry: {
        key: 'departureCountry',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'select',
    },
    departurePort: {
        key: 'departurePort',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'select',
    },
    destinationCountry: {
        key: 'destinationCountry',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'select',
    },
    destinationPort: {
        key: 'destPort',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'select',
    },
    transportationWay: {
        key: 'transport',
        ismodify: false,
        isDefaultEdit: true,
        isDefaultValue:true,
        rules: [],
        type: 'select',
    },
    customerAgreementNo: {
        key: 'customerAgreementNo',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    customerAgreementDt: {
        key: 'customerAgreementDt',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'datepicker',
    },
    remark: {
        key: 'remark',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'textarea',
    },

}
