export default {
    id:{
        _hide:true,
    },
    orderNo:{},
    skuCustomerSkuCode:{},
    skuBarCode:{},
    skuCode:{},
    supplierName:{},
    //中文品名
    skuNameEn:{},
    skuNameCustomer:{},
    skuDescEn:{},
    //中文材质
    //英文材质
    //单价
    totalQty:{},
    totalSkuPrice:{},
    entryDt:{},
    deliveryDt:{},
    //发运日期
    //发运数量
    //产品状态
    incoterm:{},
    currency:{},
    incotermArea:{},
    updateDt:{},
    // remark:{},
}
